### ISSUE TITLE
disponibilità del corso

### ISSUE THREAD

**Issue by fponticelli** [gcanti/typescript-course#2]
Ciao Giulio, se possibile sarei interessato a leggere il materiale del corso. È disponibile un PDF?

**Comment by gcanti** [comment]
Ciao Franco, non è disponibile un PDF (è un corso che vendo come prodotto)

**Comment by fponticelli** [comment]
Se è accessibile online non mi dispiacerebbe considerare l'acquisto. Il mio indirizzo email è nel mio profilo.
